{
  "source_file": "/mnt/chromeos/removable/USB Drive/review_assistant/outputs/chunks/050ac12f9b7f_207.json",
  "summary": "### Chunk unknown \u2014 unknown\n\n# noqa: F403\n  File \"/home/km_project/venvs/review_assistant_env/lib/python3.11/site-packages/torch/functional.py\", line 7, in <module>\n    import torch.nn.functional as F\n  File \"/home/km_project/venvs/review_assistant_env/lib/python3.11/site-packages/torch/nn/__init__.py\", line 1, in <module>\n    from .modules import *  # noqa: F403\n  File \"/home/km_project/venvs/review_assistant_env/lib/python3.11/site-packages/torch/nn/modules/__init__.py\", line 35, in <module>\n    from .transformer import TransformerEncoder, TransformerDecoder, \\\n  File \"/home/km_project/venvs/review_assistant_env/lib/python3.11/site-packages/torch/nn/modules/transformer.py\", line 20, in <module>\n    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),\n/home/km_project/venvs/review_assistant_env/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)\n  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),\n2.1.2+cpu\n(review_assistant_env) km_project@penguin:~$ python3 -c \"from transformers import pipeline; print(pipeline('summarization', model='t5-small'))\"\n\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.2.6 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\n\n\u2026"
}